### ISSUE TITLE
GCF/BGC data does appear correctly in results

### ISSUE THREAD

**Issue by louwenjjr** [sdrogers/nplinker#49] opened 2021-08-18 14:52 UTC
Hi Andrew,

This time I'm running into some irregularities in the web app. Maybe I just don't fully understand what is happening, but the GCF/BGCs ids in the results do not seem to be correct.

What I did: I load my crusemann data and click on the top GCF, which selects the correct BGCs from this GCF (image 1). I checked this in the bigscape output:
15294.assembled_unknown.cluster075      1215
15294.assembled_unknown.cluster081      1215
15294.assembled_unknown.cluster083      1215
35130.assembled_unknown.cluster076      1215
ARHR01000000_KB897363.1.cluster083      1215
ARHR01000000_KB897363.1.cluster088      1215
ARHS01000000_KB897620.1.cluster087      1215
ARHS01000000_KB897620.1.cluster090      1215
ARHU01000000_KB897713.1.cluster082      1215
ARHU01000000_KB897713.1.cluster083      1215
ARHU01000000_KB897713.1.cluster086      1215
AZUS01000000_AZUS01000001.1.cluster077  1215

However when I look at the results I don't see the correct GCF id that I selected and the BGCs do not belong to the selected GCF (image 2-3).

I ran this command again: docker run --name webapp --user $(id -u):$(id -g) -p 5006:5006 -v /mnt/scratch/louwe015/NPLinker/own/nplinker_shared:/data:rw andrewramsay/nplinker

Thanks!
Joris

Image 1:
![image](https://user-images.githubusercontent.com/62542407/129912277-2898a080-a68a-4c96-97ba-852ef5d59b0e.png)

Image 2:
![image](https://user-images.githubusercontent.com/62542407/129920377-75ccb143-1289-448c-b287-46c61c2d2e12.png)

Image 3:
![image](https://user-images.githubusercontent.com/62542407/129912420-7f26343e-f5ed-44e6-9e6b-646c6ec2ee89.png)

**Comment by andrewramsay** [comment] 2021-08-18 17:30
Hmm not sure what's going on there. I'll have a look tomorrow at some point!

**Comment by andrewramsay** [comment] 2021-08-19 15:05
Could you send me the file called linker.sqlite3 for this dataset? It should be in your nplinker_shared folder, with the path nplinker_data/tables_links/<dataset name>/linker.sqlite3. That should let me check how the GCF<->BGC mappings look, I think they must be incorrect in some way to get this sort of result. 

I think there might also be another related issue with how BGCs are assigned to GCFs while parsing the files but I'm still digging into that.

**Comment by louwenjjr** [comment] 2021-08-19 15:11
Thanks a lot! Let me know if I should upload something else.

linker.sqlite3 can be found here: https://www.bioinformatics.nl/~louwe015/linker.sqlite3

**Comment by andrewramsay** [comment] 2021-08-20 11:23
Great, thanks! I guess you're using an updated version of the Crusemann dataset compared to the one on the platform? I can see your one seems to have many more BGC/GCF/Spectrum/MolFam objects even when I use the same Metcalf cutoff threshold. It shouldn't matter too much though, I think I already found some instances of similar things happening with the platform version and I'll try to get to the bottom of that today.

**Comment by louwenjjr** [comment] 2021-08-20 13:52
Yes! I'm using all spectra from this updated GNPS run that I got from Justin: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=eea136cb273a4a4ba1b5ba5ae92f2c78

And I'm now using also all antismash files instead of just the ones that are present in AS-db (AS version 3.x).

That is also why I was updating the strain mappings file with some more identifiers, if you remember the last issue I had.

**Comment by andrewramsay** [comment] 2021-08-20 14:52
OK, I think I have found some instances of the same problem in the original version of the dataset now anyway. Like I said above I believe this is down to incorrect handling of the relationships between BGCs and GCFs. 

As the code is at the moment, NPLinker parses the BiG-SCAPE "clustering" .tsv files and creates BGC objects based on each line of each of them. At the same time it uses the family IDs to create GCF objects and assigns each BGC with the same ID to the corresponding GCF. 

I think this is correct as far as it goes, but where I think I've made a mistake was in assuming each BGC would only ever be matched to a single unique family ID. From looking at the Crusemann data I have, there are multiple instances where the same BGC name is matched to multiple family IDs. For example if I search for `NZ_AZWY01000021.region001` in the bigscape clustering tsv files I get:

```
NRPS_clustering_c0.30.tsv:NZ_AZWY01000021.region001     1663
PKS-NRP_Hybrids_clustering_c0.30.tsv:NZ_AZWY01000021.region001  159
PKSother_clustering_c0.30.tsv:NZ_AZWY01000021.region001 159
```

This is what is causing the GCFs listed in the results to be incorrect in instances like your example: depending on the order the files are parsed this particular BGC might end up with its "parent" attribute set to either GCF 1663 or GCF 159. This attribute is used in the webapp to determine which set of GCFs to use as input to the scoring functions given some selection of BGCs, so it means you could select "all BGCs in GCF 1663" and the resulting set of GCFs could also include GCF 159. So then that GCF could appear in the results despite not being selected and not having any link to GCF 1663.

Does that make sense? I'm not sure what is the best way to fix this with my limited knowledge of BiG-SCAPE/genomics, very open to any advice you have! For example I could change the structure of BGC objects so that they could have multiple "parent" GCFs, would that work or am I misunderstanding how these files are intended to be parsed in some way?

**Comment by louwenjjr** [comment] 2021-08-20 14:57
Thanks for your time!
This is new to me.. I thought that with one set of parameters a BGC would only belong to one GCF. I will look into it a bit. Maybe this could be a BiGSCAPE bug somehow, or my understanding of BiGSCAPE needs some adjustment. If I can't find an answer I will ask Satria about it :).

**Comment by justinjjvanderhooft** [comment] 2021-08-20 15:00
Hi @andrewramsay, thanks for looking into this! Apologies for not having this aspect made clearer earlier on. Indeed, some BGCs, like the example above, can have multiple "parent" GCFs. The reason is that these are "hybrid" BGCs and do not fall into one specific sort (i.e., NRPS OR PKS), but have elements of both (i.e., NRPS-PKS hybrid). Therefore, antiSMASH and BiG-SCAPE handle them as such, and they will appear in the NRPS type, PKS type, and the "NRPS-PKS hybrid type". Thus if changing te structure of the BGC objects to allowing for multiple parent GCFs would not break down-stream functionalities, that is my proposed solution. Otherwise, exclusion of the hybrids could be a (temporary) solution until we know something better?

**Comment by justinjjvanderhooft** [comment] 2021-08-20 15:00
Let me know if the above is clear!

**Comment by louwenjjr** [comment] 2021-08-20 15:04
Thanks Justin :)

**Comment by andrewramsay** [comment] 2021-08-20 15:33
I think it can probably be done without requiring too many changes, but I'll need to have a bit of a think about how best to tackle it - will post back here when I have any updates!

**Comment by andrewramsay** [comment] 2021-08-24 18:09
I've been working on making the internal changes that are required to support these hybrid BGCs, I think I'll have that working pretty soon as there was less to update than I thought. 

However I'm not sure what would be best when it comes to displaying these hybrids in the webapp interface. A couple of questions:

 * how should these hybrid objects be made visible to the user? Should there be an extra column in the BGC table indicating if it's a hybrid or not?
 * should there be a similar column for GCFs indicating if any of the BGCs they contain is a hybrid?
 * how should the scoring process handle the hybrids, given that the Metcalf scoring implementation requires GCFs as input? I can think of a few different scenarios:
   1. Select a GCF with no hybrid BGCs. This would be the "normal" case where things work as before, and the scoring input would just be that single GCF
   2. Select a GCF with one or more hybrid BGCs. What should happen here? Should there be a checkbox somewhere that controls whether you want to run the scoring by taking "all parent GCFs of all the BGCs in the original GCF" versus "only the parent GCFs of the non-hybrid BGCs" (which should just be the original GCF)? The former would be like the (unintended) behaviour in the current app, the latter would prevent you from seeing GCFs you didn't select in the results
   3. Selecting multiple BGCs directly, where none are hybrids. This shouldn't change, you'll get results from the collected set of GCF parents
   4. Selecting multiple BGCs directly, where one or more are hybrids. This is pretty similar to the 2nd case. But since there isn't an original GCF selection to indicate a particular type should the assumption be that you want to see results for all the parents of all the selected BGCs? If not there would have to be some way to indicate that the scoring input should e.g. only include the parent GCFs if they had type "NRPS" 

Let me know what you think. Depending on what needs done the webapp updates will probably take a bit longer than the internal API changes but I'll hopefully be able to get it done this week.

**Comment by justinjjvanderhooft** [comment] 2021-08-24 18:42
Hi @andrewramsay thanks for further looking into this and for your good questions and suggestions on how to deal with the hybrids - my suggestions follow below after - - >

how should these hybrid objects be made visible to the user? Should there be an extra column in the BGC table indicating if it's a hybrid or not?
--> yes, that makes sense as in case of a strange link in terms of a molecular mass or class, one would know that there is another part of the BGC that likely encodes for structural elements of another chemical class

should there be a similar column for GCFs indicating if any of the BGCs they contain is a hybrid?
--> I would say that this is less needed if this is for the individual BGCs already listed.... I think this is more relevant for the BGC than for the GCF as a whole. Having said that, if it is an easy add, it would make it easier to select for "pure GCFs".... 

how should the scoring process handle the hybrids, given that the Metcalf scoring implementation requires GCFs as input?
--> good point and good suggestions. I think it is important to avoid unintended behavior in the web app. Making an option to remove or ignore (i.e., from the selected GCFs take all BGCs and ignore links to other GCFs in case of hybrids), and an option to include all the GCFs to which hybrids lead (I am aware that this could lead to some increase in the number of GCFs as some added GCFs may have other hybrids in them, but I expect that this doesn't lead to an enormous inflation of the number of GCFs) would be the ways that I could think of that make sense. The additional "class filter" you mention as a way to control the added GCFs may be nice to include if not too complicated.... 

Let me know if you can follow me @andrewramsay @louwenjjr  and if this leads to any questions....this hybrid stuff is quite challenging! But then, nature is I guess haha.

**Comment by andrewramsay** [comment] 2021-08-30 12:15
Just a quick update on this: I've got the webapp updated to handle the hybrid objects better and the tables now have an extra column for BGCs and GCFs indicating if they are hybrids or "pure" respectively. That seems to be working so far but I still need to add a couple of extra UI widgets to provide the extra options when running the scoring process. Once I've done that and finished fixing #50 too I'll generate a new Docker image containing all the recent updates.

**Comment by louwenjjr** [comment] 2021-08-30 12:48
Great!

**Comment by justinjjvanderhooft** [comment] 2021-08-30 14:25
Sounds great @andrewramsay - glad you did not run into any strange issues there :-)

**Comment by andrewramsay** [comment] 2021-08-31 16:57
I've pushed a new Docker image for you to try out. Underneath the "Configure metcalf scoring" button there should be a new checkbox labelled "Treat hybrid BGCs as non-hybrid during scoring". If the box is checked and you select one or more GCFs from the table on the right then only those GCFs should be included in the scoring. If you leave it unchecked then it will behave as it did in the last version. 

I haven't had a chance to add something similar for the case where BGCs are selected directly yet, so if you use it in that way you'll still get results for all GCFs visible in the table after selecting the BGCs you want. 

Let me know if you run into any problems due to these various internal changes.

**Comment by louwenjjr** [comment] 2021-09-03 08:57
Hey Andrew, when trying the new docker image I run into this error upon clicking a molfam/gcf:

`
table molfam_table, selected = [1172]
table_callback: query
2021-09-03 08:55:06,562 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'ModelChanged', 'model': {'id': '2756'}, 'attr': 'indices', 'new': [1172]}], 'references': []}
 error: OperationalError('no such column: bgc_table.is_hybrid',)
Traceback (most recent call last):
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/server/protocol_handler.py", line 90, in handle
    work = await handler(message, connection)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/server/session.py", line 67, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/server/session.py", line 261, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in apply_to_document
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/protocol/messages/patch_doc.py", line 100, in <lambda>
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/document/document.py", line 411, in apply_json_patch
    patched_obj.set_from_json(attr, value, models=references, setter=setter)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/core/has_props.py", line 412, in set_from_json
    descriptor.set_from_json(self, json, models, setter)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/core/property/descriptors.py", line 623, in set_from_json
    return super().set_from_json(obj, self.property.from_json(json, models), models, setter)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/core/property/descriptors.py", line 327, in set_from_json
    self._internal_set(obj, json, setter=setter)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/core/property/descriptors.py", line 786, in _internal_set
    self._real_set(obj, old, value, hint=hint, setter=setter)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/core/property/descriptors.py", line 849, in _real_set
    self._trigger(obj, old, value, hint=hint, setter=setter)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/core/property/descriptors.py", line 926, in _trigger
    obj.trigger(self.name, old, value, hint, setter)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/model.py", line 682, in trigger
    super().trigger(descriptor.name, old, new, hint=hint, setter=setter)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/util/callback_manager.py", line 163, in trigger
    self._document._notify_change(self, attr, old, new, hint, setter, invoke)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/document/document.py", line 1090, in _notify_change
    self._trigger_on_change(event)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/document/document.py", line 1180, in _trigger_on_change
    self._with_self_as_curdoc(event.callback_invoker)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/util/callback_manager.py", line 161, in invoke
    callback(attr, old, new)
  File "/app/webapp/npapp/tables_init.py", line 364, in <lambda>
    self.molfam_ds.selected.on_change('indices', lambda a, b, c: table_callback('molfam_table'))
  File "/app/webapp/npapp/tables_init.py", line 335, in table_callback
    self.linker.query()
  File "/app/webapp/npapp/linker.py", line 119, in query
    self.sqlManager.createTempTable(self.tablesInfo, constraints)
  File "/app/webapp/npapp/linker.py", line 467, in createTempTable
    return self.db.execute(finalQuery, selectedConstraints)
sqlite3.OperationalError: no such column: bgc_table.is_hybrid
on_session_destroyed
`

**Comment by andrewramsay** [comment] 2021-09-03 09:55
Ah, this is happening because it is still trying to load the version of the tables data from the previous version of the webapp. I'd added some new code to automatically detect changes to the database schema and regenerate it if needed, but it looks like there is a typo in there that probably caused this to happen. 

I'll push a new version with a fix later today, but for a quicker workaround what you can do is find the folder `<nplinker_shared>/nplinker_data/tables_links/<name of dataset>`, delete it, then re-run the webapp. That should force it to generate an updated database and it should fix that error.

**Comment by louwenjjr** [comment] 2021-09-03 09:56
Cool, I'll try that first!

**Comment by louwenjjr** [comment] 2021-09-03 10:24
That fixes that issue! Clicking on spectra, bgcs and gcfs gives expected behaviour now!

However, clicking on molfams doesnt work anymore - it doesn't select any spectra etc. It also doesn't print any error.

![image](https://user-images.githubusercontent.com/62542407/131990807-838fc0b4-d1ff-4acf-a303-04c987066ef8.png)

**Comment by andrewramsay** [comment] 2021-09-03 11:18
I have no idea what could be causing that, MolFams should be treated the same as before. I've tried a couple of different datasets here and it still works for me. Can you try pulling the latest Docker version and see what happens with that?

**Comment by louwenjjr** [comment] 2021-09-03 11:27
Now it works.. Thank you! :) Don't know what went wrong before as I was also using your (then) latest docker image. Oh well.

I also noticed that the question mark for the hybrid bgcs button is slightly misplaced:
![image](https://user-images.githubusercontent.com/62542407/131998110-c004152e-5c5c-4ef3-9803-f830a4fe6169.png)

**Comment by andrewramsay** [comment] 2021-09-03 11:44
> I also noticed that the question mark for the hybrid bgcs button is slightly misplaced:

I really need to rework the layout quite extensively, at the moment it's a very basic setup that doesn't really handle different screen sizes as well as it should so things can end up overlapping like that. I'd already noticed a couple of the other "?" buttons are not aligned properly in your other screenshot. I'll add a new issue to remind me to look into it. 

> And now the #bgcs/#spectra seem to be treated as strings instead of ints, so sorting is a bit unexpected:

Hmm the sorting behaviour shouldn't have changed at all. The bokeh library which provides the table widgets should only be sorting that way if the underlying data in the column is made up of strings, but those two columns are filled with integers since the values are just the results of doing ```len(list_of_bgcs)``` or ```len(list_of_spectra)```. I've just tried a couple of different datasets here and the sorting is still working that way. Which browser/OS are you using? Wondering if it's some obscure Javascript bug or something like that.

**Comment by louwenjjr** [comment] 2021-09-03 12:06
> I'll add a new issue to remind me to look into it.

Sounds good!

> Wondering if it's some obscure Javascript bug or something like that.

Hmm that is interesting indeed. I'm running nplinker on a linux server (Ubuntu 18.04.5 LTS) and tunneling to the webapp from my windows 10 laptop and visualising the app in Chrome.

I'm noticing now that when I just load the webapp the sorting goes properly, but after clicking 'clear selections' once, the sorting treats the tables as strings. Any idea what could happen after clicking that button?

**Comment by andrewramsay** [comment] 2021-09-03 14:20
> but after clicking 'clear selections' once, the sorting treats the tables as strings

Great catch, that led me straight to the problem! 

What's happening is that the first time the tables are populated the data is correctly typed, but when you click the button to reset things it repopulates them from an SQLite database which caches all the table rows. This database had a bunch of columns set to `TEXT` instead of `INTEGER`, so after repopulating the tables did actually have strings in place of integers. 

I've just pushed another Docker update which should fix this by explicitly setting the datatype for every individual column. If another fix I made earlier today is working correctly, this time you shouldn't have to manually delete the tables_links folder. Instead it should automatically detect the database schema has been changed and recreate it while the app is loading. If this works as intended you should see something like this in the Docker logs just before it gets to the "NPLinker server loading completed" line:

```
*** DB user_version is currently 2, expecting 3
*** DB user_version mismatch (2 vs 3), regenerating content
```

If that doesn't show up or you have to delete the file again to get it going let me know, but I hope it will work this time.

**Comment by louwenjjr** [comment] 2021-09-03 14:42
This works! Thanks!

**Closed** 2021-09-08 14:27 UTC
